## Configuration data
config = {
    "cvs_sites": ['GLASTONBURY', 'MANCHESTER', 'BLOOMFIELD','COLCHESTER','COVENTRY','EAST HARTFORD','ENFIELD','HARTFORD','MANCHESTER','NEW BRITAIN','NEWINGTON','STAFFORD SPRINGS','STAMFORD','STORRS MANSFIELD','TERRYVILLE','WEST HARTFORD','WILLIMANTIC','WINDSOR','WINDSOR LOCKS','WINSTED']
}
